import Navbar from "./Navbar";
import ProfileSection from "./ProfileSection";
import { AOSInit } from "./components/global/AosInit";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={inter.className}>
        <main className="lg:flex m-[30px] gap-10">
          <ProfileSection />
          <div className="body-right w-full max-h-screen overflow-auto no-scrollbar mt-8 lg:mt-0">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
